---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create new incident
      servicenow.itsm.incident:
        state: new
        short_description: Demo Snow Incident
